using PersonalFinanceAssistant.EntityFrameworkCore;
using Xunit;

namespace PersonalFinanceAssistant.EntityFrameworkCore;

public class PersonalFinanceAssistantEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<PersonalFinanceAssistantEntityFrameworkCoreFixture>
{

}
