using Volo.Abp;

namespace PersonalFinanceAssistant.EntityFrameworkCore;

public abstract class PersonalFinanceAssistantEntityFrameworkCoreTestBase : PersonalFinanceAssistantTestBase<PersonalFinanceAssistantEntityFrameworkCoreTestModule>
{

}
